// @ts-nocheck
export const dynamic = "force-dynamic";
import React from "react";
import BasaltNavbar from "@/components/basaltcrm-landing/BasaltNavbar";
import BasaltFooter from "@/components/basaltcrm-landing/BasaltFooter";
import GeometricBackground from "@/app/components/GeometricBackground";

export const metadata = {
    title: "Developer Terms & API Access - BasaltHQ",
    description: "API Access rules, rate limits, and AI watermark compliance terms.",
};

export default function DeveloperTermsPage() {
    return (
        <div className="min-h-screen text-white font-sans selection:bg-cyan-500/30">
            <div className="fixed inset-0 z-0">
                <GeometricBackground />
            </div>

            <div className="relative z-10 flex flex-col min-h-screen">
                <BasaltNavbar />

                <main className="py-20 md:py-32">
                    <div className="container mx-auto px-4 max-w-3xl">
                        <h1 className="text-3xl md:text-5xl font-black bg-gradient-to-r from-primary to-primary/50 bg-clip-text text-transparent italic tracking-tight uppercase leading-relaxed py-4 px-4 mb-2">Developer API Agreement</h1>
                        <p className="text-gray-400 mb-12">Last updated: March 6, 2026</p>

                        <div className="prose prose-invert prose-lg max-w-none text-gray-300 space-y-12">
                            <section>
                                <p className="lead text-xl text-gray-200">
                                    By generating an API key or utilizing the BasaltCRM REST/GraphQL API ("the API"), you ("Licensee") agree to these supplemental Developer Terms in addition to our standard Terms of Service.
                                </p>
                            </section>

                            <section>
                                <h2 className="text-2xl font-bold text-white mb-4">1. Acceptable API Usage</h2>
                                <p>
                                    You may use the API exclusively to integrate BasaltCRM with your authorized applications. Rate limits are statically enforced depending on your Workspace tier. Attempts to bypass rate limiting or conduct denial-of-service testing against the API are strictly prohibited.
                                </p>
                            </section>

                            <section>
                                <h2 className="text-2xl font-bold text-white mb-4">2. AI Output Provenance & Tampering (Revocation Trigger)</h2>
                                <p>
                                    BasaltHQ embeds cryptographically secure latent watermarks and metadata into media generated by our AI ecosystem to comply with output provenance regulations (e.g., California SB 942, AB 853).
                                </p>
                                <div className="border-l-4 border-red-500 pl-4 py-2 my-6 bg-red-500/10">
                                    <h3 className="text-white font-bold mb-2">2.1 Strict Prohibition on Stripping Metadata</h3>
                                    <p className="text-sm">
                                        You are strictly prohibited from writing code, deploying scrapers, or utilizing third-party services designed to strip, alter, or obfuscate the BasaltHQ provenance watermarks embedded in API responses.
                                    </p>
                                </div>
                                <div className="border-l-4 border-red-500 pl-4 py-2 my-6 bg-red-500/10">
                                    <h3 className="text-white font-bold mb-2">2.2 96-Hour Revocation Right (Kill Switch)</h3>
                                    <p className="text-sm">
                                        Per state regulatory frameworks, BasaltHQ reserves the explicit contractual right to instantly suspend your API keys and revoke overall platform access within <strong>96 hours</strong> of discovering systemic removal or bypassing of AI watermarks by your integrations. 
                                    </p>
                                </div>
                            </section>

                            <section>
                                <h2 className="text-2xl font-bold text-white mb-4">3. Security</h2>
                                <p>
                                    You must keep your API keys secure. Do not embed keys in client-side applications or public repositories. If a key is compromised, you must immediately regenerate it via your Workspace Settings.
                                </p>
                            </section>

                            <section>
                                <h2 className="text-2xl font-bold text-white mb-4">4. Telemetry</h2>
                                <p>
                                    BasaltHQ monitors API requests for security, performance, and geographic telemetry to calculate regional access volume strictly for regulatory threshold reporting (e.g., California MAU monitoring).
                                </p>
                            </section>
                        </div>
                    </div>
                </main>

                <BasaltFooter />
            </div>
        </div>
    );
}
