"use server";

import { prismadb } from "@/lib/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

export async function generateNanoBananaImage(prompt: string, context: string = "blog") {
    // 1. Check Authentication / OAuth Status (Mocked)
    // In a real app, we would check the 'OAuth' token stored in DB for 'google-gemini'
    // const token = await getToken("google-gemini");

    // 2. Simulate Generation Delay
    await new Promise(resolve => setTimeout(resolve, 3000));

    // 3. Generate Mock Image (or call real API if keys were present)
    // We'll use a high-quality placeholder or a dynamic text image for demo
    const seed = Math.floor(Math.random() * 1000);
    const mockUrl = `https://picsum.photos/seed/${seed}/1200/630`;
    // Or closer to "Prompt specific": `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}` which is a real free AI gen API suitable for demos!

    const finalUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1200&height=630&nologo=true`;

    // 4. Save to Media Library
    const session = await getServerSession(authOptions);
    // Note: We need a valid session to attach userId, but for background jobs we might use a system user or valid admin.
    // If called from frontend via server action, session exists.

    try {
        const mediaItem = await (prismadb as any).mediaItem.create({
            data: {
                url: finalUrl,
                filename: `nano-banana-${Date.now()}.jpg`,
                mimeType: "image/jpeg",
                size: 1024 * 500, // Mock size
                width: 1200,
                height: 630,
                title: `AI Generated: ${prompt.slice(0, 30)}...`,
                caption: `Generated by Nano Banana for prompt: "${prompt}"`,
                description: `Context: ${context}`,
                isPublic: true,
                userId: session?.user?.id, // Optional, might be null if called by system
            },
        });

        return mediaItem;
    } catch (error) {
        console.error("Failed to save generated image", error);
        throw new Error("Failed to save image to library");
    }
}
