import crypto from "crypto";
import { systemLogger } from "./logger";

export const PROVENANCE_CONSTANTS = {
    PROVIDER: "BasaltHQ",
    SIGNATURE_MARKER: Buffer.from("BASALT_AI_SIG_V1"),
};

/**
 * Generates the metadata payload compliant with SB 942 requirements.
 */
export function createLatentMetadata(modelName: string, modelVersion: string) {
    return {
        provider: PROVENANCE_CONSTANTS.PROVIDER,
        model: `${modelName}-${modelVersion}`,
        timestamp: new Date().toISOString(),
        uuid: crypto.randomUUID(),
    };
}

/**
 * Injects latent, cryptographically verifiable metadata into a media buffer.
 * For Phase 2 architectural readiness, we use an appended HMAC signature format.
 * In a production C2PA implementation, this would be encoded into specific EXIF/XMP atoms.
 */
export function injectLatentMetadata(fileBuffer: Buffer, modelName: string, modelVersion: string): Buffer {
    try {
        const metadata = createLatentMetadata(modelName, modelVersion);
        const metadataString = JSON.stringify(metadata);
        const metadataBuffer = Buffer.from(metadataString, "utf-8");
        
        const secret = process.env.PROVENANCE_SECRET || "basalt_dev_provenance_secret_2026";
        const signature = crypto.createHmac("sha256", secret)
                                .update(metadataBuffer)
                                .digest();

        // Append the marker, the 32-byte signature, and the metadata payload
        return Buffer.concat([
            fileBuffer,
            PROVENANCE_CONSTANTS.SIGNATURE_MARKER,
            signature,
            metadataBuffer
        ]);
    } catch (err) {
        systemLogger.error("[AI Provenance] Failed to inject metadata", err);
        return fileBuffer; // Fallback to original if failure
    }
}

/**
 * Extracts and verifies latent metadata from a media buffer to confirm it was generated by BasaltHQ.
 */
export function verifyLatentMetadata(fileBuffer: Buffer) {
    const markerIndex = fileBuffer.lastIndexOf(PROVENANCE_CONSTANTS.SIGNATURE_MARKER);
    
    if (markerIndex === -1) {
        return { isBasaltGenerated: false, reason: "No latent signature marker found. File was not generated by BasaltHQ or was stripped." };
    }

    try {
        const markerLength = PROVENANCE_CONSTANTS.SIGNATURE_MARKER.length;
        const signatureStart = markerIndex + markerLength;
        const metadataStart = signatureStart + 32; // SHA256 signature is exactly 32 bytes

        if (metadataStart > fileBuffer.length) {
            return { isBasaltGenerated: false, reason: "Corrupted signature length." };
        }

        const signature = fileBuffer.subarray(signatureStart, metadataStart);
        const metadataBuffer = fileBuffer.subarray(metadataStart);
        
        const secret = process.env.PROVENANCE_SECRET || "basalt_dev_provenance_secret_2026";
        const expectedSignature = crypto.createHmac("sha256", secret)
                                        .update(metadataBuffer)
                                        .digest();

        if (!crypto.timingSafeEqual(signature, expectedSignature)) {
            return { isBasaltGenerated: false, reason: "Signature mismatch. The metadata or file has been tampered with." };
        }

        const metadata = JSON.parse(metadataBuffer.toString("utf-8"));

        if (metadata.provider !== PROVENANCE_CONSTANTS.PROVIDER) {
             return { isBasaltGenerated: false, reason: "Provider mismatch. This file belongs to a different platform." };
        }

        return {
            isBasaltGenerated: true,
            metadata
        };
    } catch (error) {
        return { isBasaltGenerated: false, reason: "Failed to parse latent metadata structure." };
    }
}
