import { NextResponse } from "next/server";
import { verifyLatentMetadata } from "@/lib/ai-provenance";

export async function POST(req: Request) {
    try {
        const formData = await req.formData();
        const file = formData.get("file") as File | null;

        if (!file) {
            return NextResponse.json({ error: "No file uploaded for verification." }, { status: 400 });
        }

        // Convert the uploaded file to a Buffer
        const arrayBuffer = await file.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);

        const verification = verifyLatentMetadata(buffer);

        if (verification.isBasaltGenerated) {
            return NextResponse.json({
                success: true,
                verified: true,
                provenance: verification.metadata,
                message: "This file was cryptographically verified as authentic AI content generated by BasaltHQ."
            });
        } else {
            return NextResponse.json({
                success: true,
                verified: false,
                reason: verification.reason,
                message: "We could not verify this file as BasaltHQ generated content. It may not be ours, or the metadata was stripped."
            }, { status: 404 });
        }
    } catch (error) {
        console.error("[VerifyAPI Error]", error);
        return NextResponse.json({ error: "Internal verification failed" }, { status: 500 });
    }
}
