"use client";

import React, { useState } from "react";
import BasaltNavbar from "@/components/basaltcrm-landing/BasaltNavbar";
import BasaltFooter from "@/components/basaltcrm-landing/BasaltFooter";
import GeometricBackground from "@/app/components/GeometricBackground";
import { UploadCloud, CheckCircle2, XCircle, AlertTriangle } from "lucide-react";

export default function AIVerifyPage() {
    const [file, setFile] = useState<File | null>(null);
    const [verifying, setVerifying] = useState(false);
    const [result, setResult] = useState<{
        verified: boolean;
        message: string;
        provenance?: { provider: string; model: string; timestamp: string; uuid: string; };
    } | null>(null);

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files.length > 0) {
            setFile(e.target.files[0]);
            setResult(null); // Reset result
        }
    };

    const handleVerify = async () => {
        if (!file) return;

        setVerifying(true);
        setResult(null);

        const formData = new FormData();
        formData.append("file", file);

        try {
            const response = await fetch("/api/verify", {
                method: "POST",
                body: formData,
            });

            if (!response.ok && response.status !== 404) {
                throw new Error("Verification failed.");
            }

            const data = await response.json();
            setResult({
                verified: data.verified,
                message: data.message,
                provenance: data.provenance
            });

        } catch (error) {
            setResult({ verified: false, message: "An error occurred while verifying the file. Please try again." });
        } finally {
            setVerifying(false);
        }
    };

    return (
        <div className="min-h-screen text-white font-sans selection:bg-cyan-500/30">
            <div className="fixed inset-0 z-0">
                <GeometricBackground />
            </div>

            <div className="relative z-10 flex flex-col min-h-screen">
                <BasaltNavbar />

                <main className="flex-grow py-20 md:py-32 flex items-center justify-center">
                    <div className="container mx-auto px-4 max-w-2xl w-full">
                        <div className="text-center mb-10">
                            <h1 className="text-3xl md:text-5xl font-black bg-gradient-to-r from-primary to-primary/50 bg-clip-text text-transparent italic tracking-tight uppercase leading-relaxed mb-4">
                                Content Authenticity
                            </h1>
                            <p className="text-gray-400 max-w-lg mx-auto">
                                Upload an image, audio, or video file to verify if it was artificially generated by the BasaltHQ network and read its latent provenance.
                            </p>
                        </div>

                        <div className="bg-white/5 border border-white/10 rounded-2xl p-8 backdrop-blur-md">
                            
                            {/* Upload Area */}
                            <div className="mb-8">
                                <label 
                                    htmlFor="file-upload" 
                                    className={`relative flex flex-col items-center justify-center w-full h-48 border-2 border-dashed rounded-xl cursor-pointer transition-colors ${
                                        file ? 'border-cyan-500 bg-cyan-500/5' : 'border-white/20 bg-white/5 hover:bg-white/10 hover:border-white/30'
                                    }`}
                                >
                                    <div className="flex flex-col items-center justify-center pt-5 pb-6">
                                        <UploadCloud className={`w-10 h-10 mb-3 ${file ? 'text-cyan-500' : 'text-gray-400'}`} />
                                        <p className="mb-2 text-sm text-gray-300">
                                            <span className="font-semibold">{file ? file.name : "Click to upload"}</span> {file ? "" : "or drag and drop"}
                                        </p>
                                        {!file && <p className="text-xs text-gray-500">Supported formats: JPG, PNG, MP3, MP4</p>}
                                    </div>
                                    <input id="file-upload" type="file" className="hidden" onChange={handleFileChange} accept="image/*,audio/*,video/*" />
                                </label>
                            </div>

                            <button
                                onClick={handleVerify}
                                disabled={!file || verifying}
                                className={`w-full py-4 px-6 rounded-lg font-bold text-lg tracking-wide uppercase transition-all flex items-center justify-center gap-2 ${
                                    !file ? 'bg-gray-800 text-gray-500 cursor-not-allowed' :
                                    verifying ? 'bg-cyan-500/50 text-white cursor-wait' :
                                    'bg-cyan-500 hover:bg-cyan-400 text-black shadow-[0_0_20px_rgba(6,182,212,0.4)]'
                                }`}
                            >
                                {verifying ? (
                                    <>
                                        <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                        </svg>
                                        Verifying Origin...
                                    </>
                                ) : "Verify File Provenance"}
                            </button>

                            {/* Result Display */}
                            {result && (
                                <div className={`mt-8 p-6 rounded-xl border ${result.verified ? 'bg-green-500/10 border-green-500/30' : 'bg-red-500/10 border-red-500/30'}`}>
                                    <div className="flex items-start gap-4">
                                        {result.verified ? (
                                            <CheckCircle2 className="w-6 h-6 text-green-500 shrink-0 mt-1" />
                                        ) : (
                                            <XCircle className="w-6 h-6 text-red-500 shrink-0 mt-1" />
                                        )}
                                        <div>
                                            <h3 className={`text-lg font-bold mb-2 ${result.verified ? 'text-green-400' : 'text-red-400'}`}>
                                                {result.verified ? "BasaltHQ AI Origin Verified" : "Verification Failed"}
                                            </h3>
                                            <p className="text-gray-300 text-sm leading-relaxed mb-4">
                                                {result.message}
                                            </p>
                                            
                                            {result.verified && result.provenance && (
                                                <div className="bg-black/40 rounded-lg p-4 font-mono text-xs text-gray-400 space-y-2">
                                                    <div className="grid grid-cols-3 gap-2">
                                                        <span className="text-gray-500">Provider:</span>
                                                        <span className="col-span-2 text-cyan-400">{result.provenance.provider}</span>
                                                    </div>
                                                    <div className="grid grid-cols-3 gap-2">
                                                        <span className="text-gray-500">AI Model:</span>
                                                        <span className="col-span-2 text-green-400">{result.provenance.model}</span>
                                                    </div>
                                                    <div className="grid grid-cols-3 gap-2">
                                                        <span className="text-gray-500">Generated:</span>
                                                        <span className="col-span-2 text-white">{new Date(result.provenance.timestamp).toUTCString()}</span>
                                                    </div>
                                                    <div className="grid grid-cols-3 gap-2 overflow-hidden text-ellipsis whitespace-nowrap">
                                                        <span className="text-gray-500">UUID:</span>
                                                        <span className="col-span-2 text-white" title={result.provenance.uuid}>{result.provenance.uuid}</span>
                                                    </div>
                                                </div>
                                            )}

                                            {!result.verified && (
                                                <div className="flex items-center gap-2 mt-4 text-xs text-yellow-500/80 bg-yellow-500/10 p-3 rounded">
                                                    <AlertTriangle className="w-4 h-4 shrink-0" />
                                                    <p>This file was not generated by our systems, or its latent C2PA watermarks were intentionally stripped by a third party.</p>
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            )}

                        </div>
                    </div>
                </main>

                <BasaltFooter />
            </div>
        </div>
    );
}
